name: Build Native Minecraft Server

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.2.0'
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check build.sh
        shell: bash
        run: shellcheck build.sh
      - name: Build and run native Minecraft server
        shell: bash
        run: |
          ./build.sh
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: full-directory
          path: .
